Feat: Added an S2T transformer
BharatSahAIyak/packages pull request #99
Opened 2024-05-07 22:17 UTC by RyanWalker277

The adapter returns an Xmessage having the Minio URL of the audio file sent to it. The audio file is accessible in `Xmessage.payload.media.url`. [Refs](https://github.com/BharatSahAIyak/packages/blob/main/packages/adapters/gupshup-whatsapp/src/GupShupWhatsappAdapter.ts#L299-L303) 

### What does this transformer do?

The Speech To Text transformer takes the URL from the message and sends a request to the provided s2t service. The service then returns the extracted text in the response and the transformer then appends the text in the xmessage.payload.metadata.

### Required Configs

baseUrl: Url of the S2T service
language: Input language of the audio

2024-05-08 06:30 UTC, chinmoy12c requested changes
You also need to run the `registry_generator.ts` as demonstrated [here](https://github.com/BharatSahAIyak/uci-apis/blob/dev/src/interceptors/addUserDetails.interceptor.ts)

You need to add your transformer to orchestrator as demonstrated [here](https://github.com/BharatSahAIyak/uci-apis/blob/dev/src/interceptors/addUserDetails.interceptor.ts)

2024-05-08 06:30 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.ts
> +        }
`language` should be english by deafult.

2024-05-08 06:30 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.ts
> +export class UrlTextExtractor implements ITransformer {
Add top level doc for accepted fields just like other transformers.

2024-05-08 06:30 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.ts
> +            const response = await axios.post(`${this.baseUrl}/asr/bhashini_nisai/`, payload);
```suggestion
            const response = await axios.post(${this.baseUrl}, payload);
```

2024-05-08 06:30 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.ts
> +                model_name: "ai4bharat/conformer-hi-gpu--t4" // Assuming a default model for Hindi
```
// Assuming a default model for Hindi
```

What's this?

2024-05-08 06:30 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.ts
> +                model_name: "ai4bharat/conformer-hi-gpu--t4" // Assuming a default model for Hindi
We should optionally accept this from config.

2024-05-08 06:30 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.ts
> +            console.error("Error in UrlTextExtractor transformer:", error);
```suggestion
            console.error("Error in SpeechToTextTransformer transformer:", error);
```

2024-05-08 06:30 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.ts
> +            xmsg.payload.metaData.extractedText = extractedText;
```suggestion
            xmsg.payload.metaData.speechToTextData = extractedText;
```

2024-05-08 06:30 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.spec.ts
> +      messageType: MessageType.TEXT,
This cannot be `MessageType.TEXT` and has to be `MessageType.AUDIO`

2024-05-08 06:30 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.spec.ts
> +      baseUrl: "https://ai-tools.dev.bhasai.samagra.io",
```suggestion
      baseUrl: "https://mockurl",
```

2024-05-08 06:30 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.spec.ts
> +      "https://ai-tools.dev.bhasai.samagra.io/asr/bhashini_nisai/",
```suggestion
      "https://mockurl",
```

2024-05-08 10:43 UTC, chinmoy12c commented
you also need to update `package.json` to a newer transformer version.

2024-05-09 05:04 UTC, chinmoy12c approved these changes

2024-05-09 05:04 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.ts
> +      xmsg.payload.metaData.speechToTextData = extractedText;
can we also add a `config.persist` boolean field which if true, also persists the result to `payload.text` ?

2024-05-13 05:26 UTC, chinmoy12c commented
Hey @RyanWalker277 could you please update the PR basis the feedback?

2024-05-13 05:30 UTC, chinmoy12c commented
> Hey @RyanWalker277 could you please update the PR basis the feedback?

You also need to update the media URL handling since its an array in a message. You need to only pick the 0th index and add a node that only single media is supported in incoming message.

2024-05-13 08:13 UTC, RyanWalker277 commented
@chinmoy12c did the changes, please review.

2024-05-14 06:43 UTC, chinmoy12c commented
> @chinmoy12c did the changes, can you please review these.

Tests are failing please fix them.
Registry generator test is failing please re-run `registry_generator.ts`

2024-05-16 07:21 UTC, chinmoy12c requested changes

2024-05-16 07:21 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.spec.ts
> +      baseUrl: "https://ai-tools-proxy.dev.bhasai.samagra.io/speech-to-text",
```suggestion
      baseUrl: "http://mockbaseurl",
```

2024-05-16 07:21 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.spec.ts
> +      "https://ai-tools-proxy.dev.bhasai.samagra.io/speech-to-text",
```suggestion
      "http://mockbaseurl",
```

2024-05-16 07:21 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.spec.ts
> +    );
Use specific urls instead of globally accepting any URL. This does not guarantee that my code is hitting `http://mockbaseurl` or `http://unintended-url`

2024-05-16 07:21 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.spec.ts
> +      baseUrl: "https://ai-tools-proxy.dev.bhasai.samagra.io/speech-to-text",
```suggestion
      baseUrl: "http://mockbaseurl",
```

2024-05-16 07:21 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.spec.ts
> +      baseUrl: "https://ai-tools-proxy.dev.bhasai.samagra.io/speech-to-text",
```suggestion
      baseUrl: "http://mockbaseurl",
```

2024-05-16 07:21 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.ts
> +      const mediaUrl = xmsg.payload?.media;
`xmsg.payload.media` does not give you mediaurl. We should probably rename this to `media` since this is the entire object.
Also use types.

```
const media: MessageMedia = xmsg.payload?.media;
```

2024-05-16 07:21 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.ts
> +
Should throw if `url` is `null`

2024-05-16 07:21 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.ts
> +      });
Handle failure

2024-05-16 07:21 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.ts
> +      const extractedText = response.data?.text_read;
```suggestion
      const speechToTextData = response?.text;
```

2024-05-16 07:21 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.ts
> +        xmsg.payload.text = extractedText.join(" ");
```suggestion
        xmsg.payload.text = speechToTextData;
```

2024-05-16 07:21 UTC, chinmoy12c commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.ts
> +    } catch (error) {
Remove this `try-catch` it is unnecessary.

2024-05-16 08:15 UTC, RyanWalker277 commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.ts
> +      const extractedText = response.data?.text_read;
can't change `response.data?.text_read;`, depends on API response structure.

2024-05-16 08:20 UTC, RyanWalker277 commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.ts
> +
I think URL shouln't be null. Have added more checks in the previous blocks.

2024-05-16 08:38 UTC, RyanWalker277 commented on packages/transformers/src/modules/generic/speect_to_text/speech_to_text.transformer.spec.ts
> +    );
Didn't quite get this.

2024-05-20 06:16 UTC, merged